Feinschliff

diff --git a/bin/clusteradm b/bin/clusteradm
--- a/bin/clusteradm
+++ b/bin/clusteradm
@@ -44,7 +44,7 @@ function destroy
 #
 # VMs bauen
 #
-function destroy
+function up
 {
     cp $1/config.yaml config.yaml
     vagrant up
@@ -65,28 +65,32 @@ function destroy
 #
 function join
 {
-join=$(vagrant ssh $2 -c "kubeadm token create --print-join-command")
+[ $# -lt 2 ] && { echo "missing master"; exit 1; }
+vagrant ssh $2 -c "sudo kubeadm token create --print-join-command" | tr -d '\r' >join
 
     for file in $1/*.yaml
     do
         echo "join VMs on host ${host}"
         host=`basename $file .yaml`
         [ "${host}" = "config" ] && { continue; }        
+	scp join ${host}:lernkube/data
         for h in $(ssh ${host} '( cd ~/lernkube; find .vagrant -name private_key | grep worker | cut -d/ -f 3 )')
         do
             echo ${h}
-            ssh ${host} "( cd ~/lernkube; vagrant ssh ${h} -c \"sudo ${join}\" )"
+            ssh ${host} "cd ~/lernkube && vagrant ssh ${h} -c 'sudo bash -x /data/join'"
         done
+	ssh ${host} rm -f lernkube/data/join
     done
+rm -f join
 }
 
 ########################
 #
 #   Hauptprogramm
 
-if  [ $# -lt 3 ]
+if  [ $# -lt 2 ]
 then
-    echo 'clusteradm [status|destroy|join] template master'
+    echo 'clusteradm [status|destroy|up|join] template master'
     exit 1
 fi
 
